language: python
dist: xenial
python:
- '3.7'
install: python setup.py install
script: python -m unittest discover
deploy:
  provider: pypi
  user: childsish
  password:
    secure: L2hjwp8zGjui6+GWRnkhWPyIZBXW7YipTRgPuMxBa0Hvr2Dbve8c5CfQYIBzLx7kIRfDK2XdJoZPNejws6IBydCCocpaJDNnZj6SFNtupKvOFKgPjSrzaGAWltS17kBrT49oNrzXFAdcZjGvPlodt5L6Gwsz5xqPTIMlPdHzBh/A12AE4CLjTjldO34+ehTS+tboTgkM8FAdk86Py2XSlWqQ6dsAPvbrxz58tHu5zNbCm/2zMDF6QovtLJw5JrC0hfqg7dqH4fVZa/bryRj7St3jPMwUwa1/kLWzM6redaWIxkt2DLN4PeDQkebTJ6s2boZlAPAnadgzpCi2SiWYuV7wGqkX2vywAiP04YnoLwQ/BQqwJNksKoVIvt3eDThe8617CvevLCBXDaC6CAjf9IJkboLsFVWR52VFGZrcfv7GQLI7D0IfvYLxGXwzGnirqIHL11+ke+4U6CcfSPRH/pBgo4U7TNV6w8MrINV1sDpiBBoNA04q0dxPAHzWqa7TKEj5v9yCCMk0XUtUBl1PREkKIeh0jPghNGxJXbZVtxZ/Ypz7fzRhtsIulK9dJKUdiFmYXjLyfb326byOVPilG2imwG31OAvL1zjZ8RXKF7MqCKXngazFwh+nvj/UeUsEEquGPmUJv1Fj9nAPYe+fV1TYQSv+z0QbX1mQuU+KGY8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: childsish/dynamic-json
